In [26]:
import numpy as np

v = np.array([
    [3],
    [3]
])

theta = np.pi/4

sin_th = np.sin(theta)
cos_th = np.cos(theta)

givens_rot = np.array([[ cos_th, -sin_th],
                       [ sin_th, cos_th]])

q = 0
# print(givens_rot)
# print(v)

print(givens_rot.dot(v))

[[4.44089210e-16]
 [4.24264069e+00]]


In [39]:
# R = np.array([
#     [1, 2],
#     [3, 4]
# ])

R = np.array([
    [3, 4],
    [-4, 3]
])

v = [
    [3],
    [4]
]     


print(R.dot(v))



[[25]
 [ 0]]


In [75]:
R = np.array([
    [3, 0, 4, 0],
    [0, 1, 0, 0],
    [-4, 0, 3, 0,],
    [0, 0, 0, 1],
])

v = [
    [3],
    [0],
    [4],
    [0]
]

print(np.dot(R, v))

[[25]
 [ 0]
 [ 0]
 [ 0]]
